# Generated by Django 4.2.6 on 2024-01-15 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telescope',
            name='max_magnitude',
        ),
    ]
