# Generated by Django 4.2.6 on 2023-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eyepiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('ep_type', models.CharField(max_length=50)),
                ('field_of_view', models.PositiveIntegerField()),
                ('focal_length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('tel_type', models.CharField(max_length=50)),
                ('aperture', models.FloatField()),
                ('focal_length', models.PositiveIntegerField()),
            ],
        ),
    ]
