# Generated by Django 4.2.6 on 2023-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DS_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('catalogue_index', models.CharField(max_length=50)),
                ('size', models.FloatField()),
                ('abs_brigth', models.FloatField()),
                ('short_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='US_object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_info', models.CharField(max_length=200)),
            ],
        ),
    ]
